<?xml version="1.0" standalone="yes"?>
<!-- creating a Document Type Definition . We will use an internal dtd specification -->
<!DOCTYPE library [
<!ELEMENT library (Issued)*>
<!ATTLIST Issued to CDATA "Student">
<!ELEMENT Issued (Bkid,Date, Details)>
<!ELEMENT Bkid (#PCDATA)*>
<!ELEMENT Date (#PCDATA)*>
<!ELEMENT Details (name, id)*>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT id (#PCDATA)*>
]>
<library>
    <issued to="Faculty">
        <Bkid>C001</Bkid>
        <Date>05/05/2020</Date>
        <Details>
            <name>Peter</name>
            <id>f001</id>
        </Details>
    </issued>
    <issued to="Student">
        <Bkid>JV001</Bkid>
        <Date>06/05/2020</Date>
        <Details>
            <name>Paul</name>
            <id>st001</id>
        </Details>
    </issued>
</library>